spring:
  application:
    name: ED-Module
  datasource:
         driver-class-name: com.mysql.cj.jdbc.Driver
         password: abcd
         url: jdbc:mysql://localhost:3306/nallaballe
         username: root
  jpa:
        hibernate:
           ddl-auto: update
           show-sql: true
    
server:
   port : 1006
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'

